left:
  shoulder:
    pitch:
      can_id: 14
      lower_limit: -89.9000015258789
      upper_limit: 88.0999984741211
      direction: 1
      zero_offset: 30.0
      limit_range: true
    roll:
      can_id: 13
      direction: -1
      zero_offset: 113.5999984741211
      lower_limit: -77.50000762939453
      upper_limit: 100.79999828338623
      limit_range: true
    yaw:
      can_id: 12
      lower_limit: -155.6999969482422
      upper_limit: 5.8000030517578125
      direction: 1
      zero_offset: -160.1999969482422
      limit_range: true
  elbow:
    pitch:
      can_id: 11
      direction: -1
      zero_offset: -101.80000305175781
      lower_limit: -84.50000286102295
      upper_limit: 75.09999084472656
      limit_range: true
    roll:
      can_id: 104
      lower_limit: -143.8000030517578
      upper_limit: 117.99998474121094
      direction: 1
      zero_offset: 150.8000030517578
      limit_range: true
  wrist:
    pitch:
      can_id: 22
      lower_limit: -93.62410736083984
      upper_limit: 97.66764450073242
      direction: 1
      zero_offset: -40.4899787902832
      limit_range: true
  gripper:
    open_close:
      can_id: 21
      lower_limit: 0
      upper_limit: 100
      direction: 1
      zero_offset: 0
      limit_range: true
