left:
  shoulder:
    pitch:
      can_id: 14
      lower_limit: -77.4000015258789
      upper_limit: 80.9000015258789
      direction: 1
      zero_offset: 36.0
      limit_range: true
    roll:
      can_id: 13
      direction: -1
      zero_offset: 151.1999969482422
      lower_limit: -112.69999694824219
      upper_limit: 89.0999984741211
      limit_range: true
    yaw:
      can_id: 12
      lower_limit: -75.5
      upper_limit: 5.4000091552734375
      direction: 1
      zero_offset: -160.6999969482422
      limit_range: true
  elbow:
    pitch:
      can_id: 10
      direction: -1
      zero_offset: -105.5
      lower_limit: -37.400001525878906
      upper_limit: 47.19999694824219
      limit_range: true
    roll:
      can_id: 23
      lower_limit: -46.099998474121094
      upper_limit: 36.0
      direction: 1
      zero_offset: -129.5
      limit_range: true
  wrist:
    pitch:
      can_id: 22
      lower_limit: -79.4389533996582
      upper_limit: 90.47671127319336
      direction: 1
      zero_offset: 55.15598678588867
      limit_range: true
  gripper:
    open_close:
      can_id: 21
      lower_limit: 0
      upper_limit: 100
      direction: 1
      zero_offset: 0
      limit_range: true
